### ISSUE TITLE
about training

### ISSUE THREAD

**Issue by gudwns1215** [auspicious3000/autovc#2] opened 2019-05-16 15:37 UTC
Hi! thanks for sharing this awesome code!

I hear your sample sounds and I run the .ipynb files

and I want to train autovc with my own dataset, but there is no train code...

is there any plan that sharing train code?

**Comment by rahulbhalley** [comment] 2019-05-18 16:28
I also need the code. But their README sounds like they are taking responsibility like OpenAI did for its GPT-2 model. LOL. I mean why? R u kidding me? When some researchers take actions like these it makes me wonder wth in this world GANs were invented then? They are the most powerful models than all of the other researches (not using GAN). Ian Goodfellow just took the responsibility to differentiate between real and fake (as much as I'm aware) at Google starting an ML Security subfield. 

I believe everyone must give all the code (unless it concerns some enterprise) or just stop showing off your capabilities because they are of no use to us if we can't do those experiments ourselves. Just stop publishing paper and their results too if you wanna just show off.

**Comment by auspicious3000** [comment] 2019-05-19 03:23
As authors, we certainly appreciate your concerns, and we thank you for your interest in our method. On the other hand, as researchers from IBM, while we are committed to ensuring that our results can be verified and reproduced, we also must balance those considerations against potential misuse of the technology, per our company's policy. We believe that withholding a small fraction of code is a workable compromise that allows the community to nonetheless easily understand and evaluate the method.  If you'd like to discuss further, please contact us at yang.zhang2@ibm.com.

**Closed by auspicious3000** 2019-05-19 03:23 UTC
